const words = [
    'tie', 'ape', 'row', 'oak', 'spy', 'joy', 'zip', 'nut', 'owl', 'van',
    'gem', 'ice', 'yak', 'jar', 'jet', 'job', 'kid', 'lab', 'lid', 'log',
    'mad', 'map', 'mug', 'nun', 'oar', 'odd', 'oil', 'paw', 'pea', 'pen',
    'pie', 'pig', 'pin', 'pot', 'pub', 'pug', 'rat', 'ray', 'rib', 'rim',
    'rug', 'saw', 'sea', 'tag', 'tan', 'tar', 'tea', 'ten', 'toe', 'tub',
    'urn', 'use', 'vet', 'wax', 'web', 'wig', 'win', 'yam', 'zap', 'ace',
    'act', 'add', 'age', 'ago', 'aid', 'aim', 'air', 'ale', 'all', 'ant',
    'arc', 'arm', 'art', 'ash', 'ask', 'axe', 'bag', 'bat', 'bay', 'bed',
    'bee', 'bet', 'bit', 'bow', 'box', 'boy', 'bun', 'bus', 'cab', 'can',
    'cap', 'car', 'cat', 'cow', 'cry', 'cup', 'cut', 'day', 'den', 'dew',
    'dig', 'dog', 'dot', 'dry', 'dye', 'ear', 'eat', 'egg', 'elf', 'end',
    'eye', 'fan', 'far', 'fat', 'fax', 'fig', 'fin', 'fit', 'fix', 'fly',
    'fog', 'fox', 'fun', 'fur', 'gap', 'gas', 'gel', 'gem', 'get', 'gig',
    'gin', 'god', 'gun', 'gut', 'gym', 'ham', 'hat', 'hay', 'hen', 'hip',
    'hit', 'hop', 'hot', 'how', 'hub', 'hug', 'hum', 'hut', 'ice', 'ink',
    'ion', 'jam', 'jar', 'jaw', 'jet', 'jig', 'job', 'jog', 'joy', 'jug',
    'key', 'kid', 'kin', 'kit', 'lab', 'lap', 'law', 'lay', 'leg', 'let',
    'lid', 'lie', 'lip', 'lit', 'log', 'lot', 'low', 'mad', 'man', 'map',
    'mat', 'may', 'men', 'met', 'mix', 'mob', 'mop', 'mud', 'mug', 'nag',
    'nap', 'net', 'new', 'nod', 'not', 'now', 'nut', 'oak', 'oar', 'odd',
    'off', 'oil', 'old', 'one', 'orb', 'ore', 'owl', 'own', 'pad', 'pan',
    'pat', 'paw', 'pay', 'pea', 'pen', 'pet', 'pie', 'pig', 'pin', 'pit',
    'pot', 'pox', 'pub', 'pug', 'pun', 'put', 'rag', 'ram', 'ran', 'rat',
    'raw', 'ray', 'red', 'rib', 'rid', 'rig', 'rim', 'rip', 'rod', 'row',
    'rub', 'rug', 'rum', 'run', 'rut', 'sad', 'saw', 'say', 'sea', 'see',
    'set', 'sew', 'sex', 'she', 'sip', 'sir', 'sit', 'six', 'ski', 'sky',
    'sly', 'sob', 'son', 'spy', 'sub', 'sum', 'sun', 'tab', 'tag', 'tan',
    'tap', 'tar', 'tea', 'tee', 'ten', 'the', 'tie', 'tin', 'tip', 'toe',
    'ton', 'too', 'top', 'toy', 'try', 'tub', 'tug', 'urn', 'use', 'van',
    'vat', 'vet', 'vie', 'wag', 'war', 'was', 'wax', 'way', 'web', 'wed',
    'wet', 'who', 'wig', 'win', 'wit', 'won', 'wow', 'wry', 'yak', 'yam',
    'yap', 'yaw', 'yes', 'yet', 'yew', 'yip', 'yow', 'zap', 'zig', 'zip',
    'zoo'
];

export default words;
